# Generated by Django 5.0.1 on 2026-04-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='webhook_url',
            field=models.URLField(blank=True, help_text='Optional URL to receive async callback upon completion', null=True),
        ),
    ]
